# Generated by Django 5.1.1 on 2024-09-19 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authenticate', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='id',
            field=models.CharField(editable=False, primary_key=True, serialize=False),
        ),
    ]
